apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gitops-kubeletconfig-rbac.yaml
- kubelet-config-master.yaml
- kubelet-config-worker.yaml
- kubelet-sysctls-master.yaml
- kubelet-job-master.yaml
- kubelet-job-worker.yaml
