apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusOperator: {}
    prometheusK8s:
      retention: 15d
      volumeClaimTemplate:
        metadata:
          name: gp2-pvc-prometheus
        spec:
          storageClassName: gp2
          resources:
            requests:
              storage: 200Gi
    alertmanagerMain:
      volumeClaimTemplate:
        metadata:
          name: gp2-pvc-alertmanager
        spec:
          storageClassName: gp2
          resources:
            requests:
              storage: 5Gi
    kubeStateMetrics: {}
    grafana: {}
    telemeterClient: {}
    k8sPrometheusAdapter: {}
    openshiftStateMetrics: {}
    thanosQuerier: {}
