apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gitops-machineconfig-rbac.yaml
- chrony-master.yaml
- chrony-worker.yaml
- synctime-job-master.yaml
- synctime-job-worker.yaml
