apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-compliance-remediation
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/compliance-remediation
    repoURL: https://github.com/cheevatee/ocp-gitops-cluster-config
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
